allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  c64a236f-5597-476e-ba55-a35beff389be:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2de70fd3-388c-44c4-80c9-8b67ed59a656
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e3bfa31f-a518-4622-b6f3-b19059c7ac40 # Quote Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e9b0c53-6142-4c6e-8e87-91bef9effd5e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c8f51d95-01e0-4ece-bd6e-2e504b89677f # Attribution
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dde3c3a0-29cc-4c35-9a94-44b81f1bf6d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9bbd67a1-2848-4dd1-8b61-a72efafab488 # Source Chapter
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68932849-78c4-4e22-836a-16576d377456
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d3b572f1-41e8-4263-b3a0-e9113d0d7d34 # Context Note
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 562fbbcd-9673-487e-9626-729a7f25afe0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 84aa7e6e-7e89-44ec-9197-2155404d9e12 # Is Featured
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1f9c8ba-7df9-4373-998b-6d1617523374
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f955009a-ccdb-4082-ba2a-4747ffda2fa2
        userCondition: null
    thumbFieldKey: null
handle: quotes
hasTitleField: true
icon: null
name: Quotes
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{quoteText|slice(0, 60)}...'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
