baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-CA
name: 'Light Inside the Tunnel'
primary: true
siteGroup: 5ecc5a6f-0360-4201-b030-a22a6549b701 # The Light Inside the Tunnel
sortOrder: 1
