defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 42e4cf20-f7f4-419e-85fa-9b524ebb34b5 # Philosophical Contributions
handle: contributions
maxAuthors: 1
name: 'Philosophical Contributions'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ffd7cb28-4fcf-45d1-8bb6-7d0e05c32424: # Light Inside the Tunnel
    enabledByDefault: true
    hasUrls: true
    template: contributions/_entry
    uriFormat: 'contributions/{slug}'
type: channel
